version: "3.9"

networks:
  op1-net:
    driver: bridge

volumes:
  op1-postgres-data:
  op1-rabbitmq-data:
  op1-rabbitmq-log:
  data-protection-keys:

services:
  op1-postgres:
    image: postgres:16
    container_name: op1-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - op1-postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 15
    networks:
      - op1-net

  op1-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: op1-rabbitmq
    restart: unless-stopped
    env_file: .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      - "${RABBITMQ_HTTP_PORT:-15672}:15672"
    volumes:
      - op1-rabbitmq-data:/var/lib/rabbitmq/mnesia
      - op1-rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - op1-net

  op1-cust-onboarding-api:
    build:
      context: .
      dockerfile: dBanking.CustomerOnboarding.API/Dockerfile
    container_name: op1-cust-onboarding-api
    env_file: .env
    depends_on:
      - op1-postgres
      - op1-rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DOTNET_RUNNING_IN_CONTAINER: "true"
      ASPNETCORE_URLS: http://0.0.0.0:9090
      APPLY_MIGRATIONS: "true"
      # Swagger redirect (host-exposed API port)
      Swagger__RedirectUri: "http://localhost:${API_HTTP_PORT:-9090}/swagger/oauth2-redirect.html"

      # Postgres (app will connect via service name inside Docker network)
      DB_HOST: op1-postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PG_INCLUDE_ERROR_DETAIL: ${PG_INCLUDE_ERROR_DETAIL}

      # RabbitMQ
      RABBITMQ_HOST: op1-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: /
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_USE_TLS: "false"

      #Redis
      REDIS_HOST: op1-redis
      REDIS_PORT: 6379

    volumes:
      - data-protection-keys:/keys

    ports:
      - "${API_HTTP_PORT:-9090}:9090"

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9090/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

    networks:
      - op1-net

  op1-redis:
    container_name: op1-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - C:/Users/QL132BZ/source/op1-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 15
    networks:
      - op1-net